name: AiPlayer

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.4 # state management
  flutter:
    sdk: flutter # flutter sdk
  flutter_bloc: ^8.1.6 # state management
  flutter_cache_manager: ^3.4.1
  flutter_staggered_animations: ^1.1.1 # animation
  flutter_svg: ^2.0.13
  fluttertoast: ^8.2.8
  get_it: ^8.0.2 # dependency injection
  hive: ^2.2.3 # local database
  hive_flutter: ^1.1.0 # local database
  just_audio: ^0.9.42 # audio player
  just_audio_background: ^0.0.1-beta.13 # audio player background
  lottie: ^3.1.3
  marquee: ^2.3.0
  on_audio_query: ^2.9.0 # get songs from device
  package_info_plus: ^8.1.0 # get app info
  permission_handler: ^11.3.1 # get permission
  rxdart: ^0.28.0 # stream
  share_plus: ^10.1.1 # share song
  url_launcher: ^6.3.1 # open url
  http: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # linter
  flutter_launcher_icons: ^0.14.1 # app icon generator
  record: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/lottie/
    - assets/images/
    - assets/svg/
