# Generated by Django 5.1.5 on 2025-02-10 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_path',
            field=models.FileField(upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('title', 'artist', 'album'), name='unique_song'),
        ),
    ]
